apiVersion: v1
name: sagemaker-k8s-operator
version: 0.1.0
description: A Helm chart for deploying the SageMaker Operator for Kubernetes by assining permission using IAM role.
maintainers:
  - name: Gautam Kumar
    email: gauta@amazon.com
  - name: Cade Daniel
    email: cdnamz@amazon.com
  - name: Nicholas Thomson
    email: nithomso@amazon.com
  - name: Meghna Baijal
    email: mbaijal@amazon.com
